[package]
name = "ad2021"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aoc-runner = "0.3.0"
aoc-runner-derive = "0.3.0"
anyhow = "1.0"
nalgebra = "0.29.0"
itertools = "0.10.0"
